// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileSyncMsg.proto

package sliner.com;

public final class FileSyncMsg {
  private FileSyncMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FileSyncMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .sliner.com.FileSyncHeader header = 1;
    /**
     * <code>required .sliner.com.FileSyncHeader header = 1;</code>
     *
     * <pre>
     *test
     * </pre>
     */
    boolean hasHeader();
    /**
     * <code>required .sliner.com.FileSyncHeader header = 1;</code>
     *
     * <pre>
     *test
     * </pre>
     */
    sliner.com.FileSyncMsg.FileSyncHeader getHeader();
    /**
     * <code>required .sliner.com.FileSyncHeader header = 1;</code>
     *
     * <pre>
     *test
     * </pre>
     */
    sliner.com.FileSyncMsg.FileSyncHeaderOrBuilder getHeaderOrBuilder();
  }
  /**
   * Protobuf type {@code sliner.com.FileSyncMessage}
   *
   * <pre>
   * protoc FileSyncMessage.proto --java_out=./
   *Main message defintion.
   * </pre>
   */
  public static final class FileSyncMessage extends
      com.google.protobuf.GeneratedMessage
      implements FileSyncMessageOrBuilder {
    // Use FileSyncMessage.newBuilder() to construct.
    private FileSyncMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FileSyncMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FileSyncMessage defaultInstance;
    public static FileSyncMessage getDefaultInstance() {
      return defaultInstance;
    }

    public FileSyncMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FileSyncMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              sliner.com.FileSyncMsg.FileSyncHeader.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(sliner.com.FileSyncMsg.FileSyncHeader.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sliner.com.FileSyncMsg.internal_static_sliner_com_FileSyncMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sliner.com.FileSyncMsg.internal_static_sliner_com_FileSyncMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sliner.com.FileSyncMsg.FileSyncMessage.class, sliner.com.FileSyncMsg.FileSyncMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<FileSyncMessage> PARSER =
        new com.google.protobuf.AbstractParser<FileSyncMessage>() {
      public FileSyncMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileSyncMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FileSyncMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .sliner.com.FileSyncHeader header = 1;
    public static final int HEADER_FIELD_NUMBER = 1;
    private sliner.com.FileSyncMsg.FileSyncHeader header_;
    /**
     * <code>required .sliner.com.FileSyncHeader header = 1;</code>
     *
     * <pre>
     *test
     * </pre>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .sliner.com.FileSyncHeader header = 1;</code>
     *
     * <pre>
     *test
     * </pre>
     */
    public sliner.com.FileSyncMsg.FileSyncHeader getHeader() {
      return header_;
    }
    /**
     * <code>required .sliner.com.FileSyncHeader header = 1;</code>
     *
     * <pre>
     *test
     * </pre>
     */
    public sliner.com.FileSyncMsg.FileSyncHeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }

    private void initFields() {
      header_ = sliner.com.FileSyncMsg.FileSyncHeader.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static sliner.com.FileSyncMsg.FileSyncMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sliner.com.FileSyncMsg.FileSyncMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sliner.com.FileSyncMsg.FileSyncMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sliner.com.FileSyncMsg.FileSyncMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sliner.com.FileSyncMsg.FileSyncMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sliner.com.FileSyncMsg.FileSyncMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static sliner.com.FileSyncMsg.FileSyncMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static sliner.com.FileSyncMsg.FileSyncMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static sliner.com.FileSyncMsg.FileSyncMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sliner.com.FileSyncMsg.FileSyncMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sliner.com.FileSyncMsg.FileSyncMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sliner.com.FileSyncMessage}
     *
     * <pre>
     * protoc FileSyncMessage.proto --java_out=./
     *Main message defintion.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sliner.com.FileSyncMsg.FileSyncMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sliner.com.FileSyncMsg.internal_static_sliner_com_FileSyncMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sliner.com.FileSyncMsg.internal_static_sliner_com_FileSyncMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sliner.com.FileSyncMsg.FileSyncMessage.class, sliner.com.FileSyncMsg.FileSyncMessage.Builder.class);
      }

      // Construct using sliner.com.FileSyncMsg.FileSyncMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = sliner.com.FileSyncMsg.FileSyncHeader.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sliner.com.FileSyncMsg.internal_static_sliner_com_FileSyncMessage_descriptor;
      }

      public sliner.com.FileSyncMsg.FileSyncMessage getDefaultInstanceForType() {
        return sliner.com.FileSyncMsg.FileSyncMessage.getDefaultInstance();
      }

      public sliner.com.FileSyncMsg.FileSyncMessage build() {
        sliner.com.FileSyncMsg.FileSyncMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public sliner.com.FileSyncMsg.FileSyncMessage buildPartial() {
        sliner.com.FileSyncMsg.FileSyncMessage result = new sliner.com.FileSyncMsg.FileSyncMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sliner.com.FileSyncMsg.FileSyncMessage) {
          return mergeFrom((sliner.com.FileSyncMsg.FileSyncMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sliner.com.FileSyncMsg.FileSyncMessage other) {
        if (other == sliner.com.FileSyncMsg.FileSyncMessage.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeader()) {
          
          return false;
        }
        if (!getHeader().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sliner.com.FileSyncMsg.FileSyncMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sliner.com.FileSyncMsg.FileSyncMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .sliner.com.FileSyncHeader header = 1;
      private sliner.com.FileSyncMsg.FileSyncHeader header_ = sliner.com.FileSyncMsg.FileSyncHeader.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          sliner.com.FileSyncMsg.FileSyncHeader, sliner.com.FileSyncMsg.FileSyncHeader.Builder, sliner.com.FileSyncMsg.FileSyncHeaderOrBuilder> headerBuilder_;
      /**
       * <code>required .sliner.com.FileSyncHeader header = 1;</code>
       *
       * <pre>
       *test
       * </pre>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .sliner.com.FileSyncHeader header = 1;</code>
       *
       * <pre>
       *test
       * </pre>
       */
      public sliner.com.FileSyncMsg.FileSyncHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .sliner.com.FileSyncHeader header = 1;</code>
       *
       * <pre>
       *test
       * </pre>
       */
      public Builder setHeader(sliner.com.FileSyncMsg.FileSyncHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .sliner.com.FileSyncHeader header = 1;</code>
       *
       * <pre>
       *test
       * </pre>
       */
      public Builder setHeader(
          sliner.com.FileSyncMsg.FileSyncHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .sliner.com.FileSyncHeader header = 1;</code>
       *
       * <pre>
       *test
       * </pre>
       */
      public Builder mergeHeader(sliner.com.FileSyncMsg.FileSyncHeader value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != sliner.com.FileSyncMsg.FileSyncHeader.getDefaultInstance()) {
            header_ =
              sliner.com.FileSyncMsg.FileSyncHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .sliner.com.FileSyncHeader header = 1;</code>
       *
       * <pre>
       *test
       * </pre>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = sliner.com.FileSyncMsg.FileSyncHeader.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .sliner.com.FileSyncHeader header = 1;</code>
       *
       * <pre>
       *test
       * </pre>
       */
      public sliner.com.FileSyncMsg.FileSyncHeader.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .sliner.com.FileSyncHeader header = 1;</code>
       *
       * <pre>
       *test
       * </pre>
       */
      public sliner.com.FileSyncMsg.FileSyncHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      /**
       * <code>required .sliner.com.FileSyncHeader header = 1;</code>
       *
       * <pre>
       *test
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          sliner.com.FileSyncMsg.FileSyncHeader, sliner.com.FileSyncMsg.FileSyncHeader.Builder, sliner.com.FileSyncMsg.FileSyncHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              sliner.com.FileSyncMsg.FileSyncHeader, sliner.com.FileSyncMsg.FileSyncHeader.Builder, sliner.com.FileSyncMsg.FileSyncHeaderOrBuilder>(
                  header_,
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:sliner.com.FileSyncMessage)
    }

    static {
      defaultInstance = new FileSyncMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sliner.com.FileSyncMessage)
  }

  public interface FileSyncHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .sliner.com.FileSyncHeader.FileSyncVersion version = 1;
    /**
     * <code>required .sliner.com.FileSyncHeader.FileSyncVersion version = 1;</code>
     */
    boolean hasVersion();
    /**
     * <code>required .sliner.com.FileSyncHeader.FileSyncVersion version = 1;</code>
     */
    sliner.com.FileSyncMsg.FileSyncHeader.FileSyncVersion getVersion();

    // required .sliner.com.FileSyncHeader.FileSyncMessageType msg_type = 2;
    /**
     * <code>required .sliner.com.FileSyncHeader.FileSyncMessageType msg_type = 2;</code>
     */
    boolean hasMsgType();
    /**
     * <code>required .sliner.com.FileSyncHeader.FileSyncMessageType msg_type = 2;</code>
     */
    sliner.com.FileSyncMsg.FileSyncHeader.FileSyncMessageType getMsgType();
  }
  /**
   * Protobuf type {@code sliner.com.FileSyncHeader}
   */
  public static final class FileSyncHeader extends
      com.google.protobuf.GeneratedMessage
      implements FileSyncHeaderOrBuilder {
    // Use FileSyncHeader.newBuilder() to construct.
    private FileSyncHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FileSyncHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FileSyncHeader defaultInstance;
    public static FileSyncHeader getDefaultInstance() {
      return defaultInstance;
    }

    public FileSyncHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FileSyncHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              sliner.com.FileSyncMsg.FileSyncHeader.FileSyncVersion value = sliner.com.FileSyncMsg.FileSyncHeader.FileSyncVersion.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                version_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              sliner.com.FileSyncMsg.FileSyncHeader.FileSyncMessageType value = sliner.com.FileSyncMsg.FileSyncHeader.FileSyncMessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                msgType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sliner.com.FileSyncMsg.internal_static_sliner_com_FileSyncHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sliner.com.FileSyncMsg.internal_static_sliner_com_FileSyncHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sliner.com.FileSyncMsg.FileSyncHeader.class, sliner.com.FileSyncMsg.FileSyncHeader.Builder.class);
    }

    public static com.google.protobuf.Parser<FileSyncHeader> PARSER =
        new com.google.protobuf.AbstractParser<FileSyncHeader>() {
      public FileSyncHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileSyncHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FileSyncHeader> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code sliner.com.FileSyncHeader.FileSyncVersion}
     */
    public enum FileSyncVersion
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>VERSION_ONE = 1;</code>
       */
      VERSION_ONE(0, 1),
      ;

      /**
       * <code>VERSION_ONE = 1;</code>
       */
      public static final int VERSION_ONE_VALUE = 1;


      public final int getNumber() { return value; }

      public static FileSyncVersion valueOf(int value) {
        switch (value) {
          case 1: return VERSION_ONE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<FileSyncVersion>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<FileSyncVersion>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FileSyncVersion>() {
              public FileSyncVersion findValueByNumber(int number) {
                return FileSyncVersion.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sliner.com.FileSyncMsg.FileSyncHeader.getDescriptor().getEnumTypes().get(0);
      }

      private static final FileSyncVersion[] VALUES = values();

      public static FileSyncVersion valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private FileSyncVersion(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:sliner.com.FileSyncHeader.FileSyncVersion)
    }

    /**
     * Protobuf enum {@code sliner.com.FileSyncHeader.FileSyncMessageType}
     */
    public enum FileSyncMessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HELLO_MSG = 1;</code>
       */
      HELLO_MSG(0, 1),
      /**
       * <code>DIR_EXCHANGE = 2;</code>
       */
      DIR_EXCHANGE(1, 2),
      ;

      /**
       * <code>HELLO_MSG = 1;</code>
       */
      public static final int HELLO_MSG_VALUE = 1;
      /**
       * <code>DIR_EXCHANGE = 2;</code>
       */
      public static final int DIR_EXCHANGE_VALUE = 2;


      public final int getNumber() { return value; }

      public static FileSyncMessageType valueOf(int value) {
        switch (value) {
          case 1: return HELLO_MSG;
          case 2: return DIR_EXCHANGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<FileSyncMessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<FileSyncMessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FileSyncMessageType>() {
              public FileSyncMessageType findValueByNumber(int number) {
                return FileSyncMessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sliner.com.FileSyncMsg.FileSyncHeader.getDescriptor().getEnumTypes().get(1);
      }

      private static final FileSyncMessageType[] VALUES = values();

      public static FileSyncMessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private FileSyncMessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:sliner.com.FileSyncHeader.FileSyncMessageType)
    }

    private int bitField0_;
    // required .sliner.com.FileSyncHeader.FileSyncVersion version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private sliner.com.FileSyncMsg.FileSyncHeader.FileSyncVersion version_;
    /**
     * <code>required .sliner.com.FileSyncHeader.FileSyncVersion version = 1;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .sliner.com.FileSyncHeader.FileSyncVersion version = 1;</code>
     */
    public sliner.com.FileSyncMsg.FileSyncHeader.FileSyncVersion getVersion() {
      return version_;
    }

    // required .sliner.com.FileSyncHeader.FileSyncMessageType msg_type = 2;
    public static final int MSG_TYPE_FIELD_NUMBER = 2;
    private sliner.com.FileSyncMsg.FileSyncHeader.FileSyncMessageType msgType_;
    /**
     * <code>required .sliner.com.FileSyncHeader.FileSyncMessageType msg_type = 2;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .sliner.com.FileSyncHeader.FileSyncMessageType msg_type = 2;</code>
     */
    public sliner.com.FileSyncMsg.FileSyncHeader.FileSyncMessageType getMsgType() {
      return msgType_;
    }

    private void initFields() {
      version_ = sliner.com.FileSyncMsg.FileSyncHeader.FileSyncVersion.VERSION_ONE;
      msgType_ = sliner.com.FileSyncMsg.FileSyncHeader.FileSyncMessageType.HELLO_MSG;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, version_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, msgType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, version_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, msgType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static sliner.com.FileSyncMsg.FileSyncHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sliner.com.FileSyncMsg.FileSyncHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sliner.com.FileSyncMsg.FileSyncHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sliner.com.FileSyncMsg.FileSyncHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sliner.com.FileSyncMsg.FileSyncHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sliner.com.FileSyncMsg.FileSyncHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static sliner.com.FileSyncMsg.FileSyncHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static sliner.com.FileSyncMsg.FileSyncHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static sliner.com.FileSyncMsg.FileSyncHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sliner.com.FileSyncMsg.FileSyncHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sliner.com.FileSyncMsg.FileSyncHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sliner.com.FileSyncHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sliner.com.FileSyncMsg.FileSyncHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sliner.com.FileSyncMsg.internal_static_sliner_com_FileSyncHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sliner.com.FileSyncMsg.internal_static_sliner_com_FileSyncHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sliner.com.FileSyncMsg.FileSyncHeader.class, sliner.com.FileSyncMsg.FileSyncHeader.Builder.class);
      }

      // Construct using sliner.com.FileSyncMsg.FileSyncHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = sliner.com.FileSyncMsg.FileSyncHeader.FileSyncVersion.VERSION_ONE;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = sliner.com.FileSyncMsg.FileSyncHeader.FileSyncMessageType.HELLO_MSG;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sliner.com.FileSyncMsg.internal_static_sliner_com_FileSyncHeader_descriptor;
      }

      public sliner.com.FileSyncMsg.FileSyncHeader getDefaultInstanceForType() {
        return sliner.com.FileSyncMsg.FileSyncHeader.getDefaultInstance();
      }

      public sliner.com.FileSyncMsg.FileSyncHeader build() {
        sliner.com.FileSyncMsg.FileSyncHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public sliner.com.FileSyncMsg.FileSyncHeader buildPartial() {
        sliner.com.FileSyncMsg.FileSyncHeader result = new sliner.com.FileSyncMsg.FileSyncHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgType_ = msgType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sliner.com.FileSyncMsg.FileSyncHeader) {
          return mergeFrom((sliner.com.FileSyncMsg.FileSyncHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sliner.com.FileSyncMsg.FileSyncHeader other) {
        if (other == sliner.com.FileSyncMsg.FileSyncHeader.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasMsgType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sliner.com.FileSyncMsg.FileSyncHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sliner.com.FileSyncMsg.FileSyncHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .sliner.com.FileSyncHeader.FileSyncVersion version = 1;
      private sliner.com.FileSyncMsg.FileSyncHeader.FileSyncVersion version_ = sliner.com.FileSyncMsg.FileSyncHeader.FileSyncVersion.VERSION_ONE;
      /**
       * <code>required .sliner.com.FileSyncHeader.FileSyncVersion version = 1;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .sliner.com.FileSyncHeader.FileSyncVersion version = 1;</code>
       */
      public sliner.com.FileSyncMsg.FileSyncHeader.FileSyncVersion getVersion() {
        return version_;
      }
      /**
       * <code>required .sliner.com.FileSyncHeader.FileSyncVersion version = 1;</code>
       */
      public Builder setVersion(sliner.com.FileSyncMsg.FileSyncHeader.FileSyncVersion value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .sliner.com.FileSyncHeader.FileSyncVersion version = 1;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = sliner.com.FileSyncMsg.FileSyncHeader.FileSyncVersion.VERSION_ONE;
        onChanged();
        return this;
      }

      // required .sliner.com.FileSyncHeader.FileSyncMessageType msg_type = 2;
      private sliner.com.FileSyncMsg.FileSyncHeader.FileSyncMessageType msgType_ = sliner.com.FileSyncMsg.FileSyncHeader.FileSyncMessageType.HELLO_MSG;
      /**
       * <code>required .sliner.com.FileSyncHeader.FileSyncMessageType msg_type = 2;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .sliner.com.FileSyncHeader.FileSyncMessageType msg_type = 2;</code>
       */
      public sliner.com.FileSyncMsg.FileSyncHeader.FileSyncMessageType getMsgType() {
        return msgType_;
      }
      /**
       * <code>required .sliner.com.FileSyncHeader.FileSyncMessageType msg_type = 2;</code>
       */
      public Builder setMsgType(sliner.com.FileSyncMsg.FileSyncHeader.FileSyncMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .sliner.com.FileSyncHeader.FileSyncMessageType msg_type = 2;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgType_ = sliner.com.FileSyncMsg.FileSyncHeader.FileSyncMessageType.HELLO_MSG;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sliner.com.FileSyncHeader)
    }

    static {
      defaultInstance = new FileSyncHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sliner.com.FileSyncHeader)
  }

  public interface FileSyncDirExchangeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string directory = 1;
    /**
     * <code>required string directory = 1;</code>
     */
    boolean hasDirectory();
    /**
     * <code>required string directory = 1;</code>
     */
    java.lang.String getDirectory();
    /**
     * <code>required string directory = 1;</code>
     */
    com.google.protobuf.ByteString
        getDirectoryBytes();
  }
  /**
   * Protobuf type {@code sliner.com.FileSyncDirExchange}
   */
  public static final class FileSyncDirExchange extends
      com.google.protobuf.GeneratedMessage
      implements FileSyncDirExchangeOrBuilder {
    // Use FileSyncDirExchange.newBuilder() to construct.
    private FileSyncDirExchange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FileSyncDirExchange(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FileSyncDirExchange defaultInstance;
    public static FileSyncDirExchange getDefaultInstance() {
      return defaultInstance;
    }

    public FileSyncDirExchange getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FileSyncDirExchange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              directory_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sliner.com.FileSyncMsg.internal_static_sliner_com_FileSyncDirExchange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sliner.com.FileSyncMsg.internal_static_sliner_com_FileSyncDirExchange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sliner.com.FileSyncMsg.FileSyncDirExchange.class, sliner.com.FileSyncMsg.FileSyncDirExchange.Builder.class);
    }

    public static com.google.protobuf.Parser<FileSyncDirExchange> PARSER =
        new com.google.protobuf.AbstractParser<FileSyncDirExchange>() {
      public FileSyncDirExchange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileSyncDirExchange(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FileSyncDirExchange> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string directory = 1;
    public static final int DIRECTORY_FIELD_NUMBER = 1;
    private java.lang.Object directory_;
    /**
     * <code>required string directory = 1;</code>
     */
    public boolean hasDirectory() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string directory = 1;</code>
     */
    public java.lang.String getDirectory() {
      java.lang.Object ref = directory_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          directory_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string directory = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDirectoryBytes() {
      java.lang.Object ref = directory_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        directory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      directory_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDirectory()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDirectoryBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDirectoryBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static sliner.com.FileSyncMsg.FileSyncDirExchange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sliner.com.FileSyncMsg.FileSyncDirExchange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sliner.com.FileSyncMsg.FileSyncDirExchange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sliner.com.FileSyncMsg.FileSyncDirExchange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sliner.com.FileSyncMsg.FileSyncDirExchange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sliner.com.FileSyncMsg.FileSyncDirExchange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static sliner.com.FileSyncMsg.FileSyncDirExchange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static sliner.com.FileSyncMsg.FileSyncDirExchange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static sliner.com.FileSyncMsg.FileSyncDirExchange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sliner.com.FileSyncMsg.FileSyncDirExchange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sliner.com.FileSyncMsg.FileSyncDirExchange prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sliner.com.FileSyncDirExchange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sliner.com.FileSyncMsg.FileSyncDirExchangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sliner.com.FileSyncMsg.internal_static_sliner_com_FileSyncDirExchange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sliner.com.FileSyncMsg.internal_static_sliner_com_FileSyncDirExchange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sliner.com.FileSyncMsg.FileSyncDirExchange.class, sliner.com.FileSyncMsg.FileSyncDirExchange.Builder.class);
      }

      // Construct using sliner.com.FileSyncMsg.FileSyncDirExchange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        directory_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sliner.com.FileSyncMsg.internal_static_sliner_com_FileSyncDirExchange_descriptor;
      }

      public sliner.com.FileSyncMsg.FileSyncDirExchange getDefaultInstanceForType() {
        return sliner.com.FileSyncMsg.FileSyncDirExchange.getDefaultInstance();
      }

      public sliner.com.FileSyncMsg.FileSyncDirExchange build() {
        sliner.com.FileSyncMsg.FileSyncDirExchange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public sliner.com.FileSyncMsg.FileSyncDirExchange buildPartial() {
        sliner.com.FileSyncMsg.FileSyncDirExchange result = new sliner.com.FileSyncMsg.FileSyncDirExchange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.directory_ = directory_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sliner.com.FileSyncMsg.FileSyncDirExchange) {
          return mergeFrom((sliner.com.FileSyncMsg.FileSyncDirExchange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sliner.com.FileSyncMsg.FileSyncDirExchange other) {
        if (other == sliner.com.FileSyncMsg.FileSyncDirExchange.getDefaultInstance()) return this;
        if (other.hasDirectory()) {
          bitField0_ |= 0x00000001;
          directory_ = other.directory_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDirectory()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sliner.com.FileSyncMsg.FileSyncDirExchange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sliner.com.FileSyncMsg.FileSyncDirExchange) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string directory = 1;
      private java.lang.Object directory_ = "";
      /**
       * <code>required string directory = 1;</code>
       */
      public boolean hasDirectory() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string directory = 1;</code>
       */
      public java.lang.String getDirectory() {
        java.lang.Object ref = directory_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          directory_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string directory = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDirectoryBytes() {
        java.lang.Object ref = directory_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          directory_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string directory = 1;</code>
       */
      public Builder setDirectory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        directory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string directory = 1;</code>
       */
      public Builder clearDirectory() {
        bitField0_ = (bitField0_ & ~0x00000001);
        directory_ = getDefaultInstance().getDirectory();
        onChanged();
        return this;
      }
      /**
       * <code>required string directory = 1;</code>
       */
      public Builder setDirectoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        directory_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sliner.com.FileSyncDirExchange)
    }

    static {
      defaultInstance = new FileSyncDirExchange(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sliner.com.FileSyncDirExchange)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sliner_com_FileSyncMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sliner_com_FileSyncMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sliner_com_FileSyncHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sliner_com_FileSyncHeader_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sliner_com_FileSyncDirExchange_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sliner_com_FileSyncDirExchange_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021FileSyncMsg.proto\022\nsliner.com\"=\n\017FileS" +
      "yncMessage\022*\n\006header\030\001 \002(\0132\032.sliner.com." +
      "FileSyncHeader\"\353\001\n\016FileSyncHeader\022;\n\007ver" +
      "sion\030\001 \002(\0162*.sliner.com.FileSyncHeader.F" +
      "ileSyncVersion\022@\n\010msg_type\030\002 \002(\0162..sline" +
      "r.com.FileSyncHeader.FileSyncMessageType" +
      "\"\"\n\017FileSyncVersion\022\017\n\013VERSION_ONE\020\001\"6\n\023" +
      "FileSyncMessageType\022\r\n\tHELLO_MSG\020\001\022\020\n\014DI" +
      "R_EXCHANGE\020\002\"(\n\023FileSyncDirExchange\022\021\n\td" +
      "irectory\030\001 \002(\tB\003\210\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sliner_com_FileSyncMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sliner_com_FileSyncMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sliner_com_FileSyncMessage_descriptor,
              new java.lang.String[] { "Header", });
          internal_static_sliner_com_FileSyncHeader_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_sliner_com_FileSyncHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sliner_com_FileSyncHeader_descriptor,
              new java.lang.String[] { "Version", "MsgType", });
          internal_static_sliner_com_FileSyncDirExchange_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_sliner_com_FileSyncDirExchange_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sliner_com_FileSyncDirExchange_descriptor,
              new java.lang.String[] { "Directory", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
